"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-06-10 14:55:35.982535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('latest_release_date', sa.Date(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('install_method', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_apps_vendor'), ['vendor'], unique=False)

    op.create_table('autopkg_recipes',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('parent_identifier', sa.String(), nullable=True),
    sa.Column('inferred_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    with op.batch_alter_table('autopkg_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autopkg_recipes_name'), ['name'], unique=False)

    op.create_table('homebrew_casks',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('auto_updates', sa.Boolean(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('installomator_labels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('install_type', sa.String(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('expected_team_id', sa.String(), nullable=True),
    sa.Column('app_new_version', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('fragment', sa.String(), nullable=True),
    sa.Column('blob_sha', sa.String(), nullable=True),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('installomator_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installomator_labels_package_id'), ['package_id'], unique=False)

    op.create_table('jamf_app_installers',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('jamf_id', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    with op.batch_alter_table('jamf_app_installers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jamf_app_installers_bundle_id'), ['bundle_id'], unique=False)

    op.create_table('jamf_titles',
    sa.Column('name_id', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name_id')
    )
    op.create_table('mas_apps',
    sa.Column('bundle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_notes', sa.String(), nullable=True),
    sa.Column('store_url', sa.String(), nullable=True),
    sa.Column('minimum_os_version', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bundle_id')
    )
    op.create_table('app_source_details',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('installomator', sa.JSON(), nullable=True),
    sa.Column('homebrew_cask', sa.JSON(), nullable=True),
    sa.Column('autopkg', sa.JSON(), nullable=True),
    sa.Column('mas', sa.JSON(), nullable=True),
    sa.Column('jamf_app_installer', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_source_details')
    op.drop_table('mas_apps')
    op.drop_table('jamf_titles')
    with op.batch_alter_table('jamf_app_installers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jamf_app_installers_bundle_id'))

    op.drop_table('jamf_app_installers')
    with op.batch_alter_table('installomator_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installomator_labels_package_id'))

    op.drop_table('installomator_labels')
    op.drop_table('homebrew_casks')
    with op.batch_alter_table('autopkg_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autopkg_recipes_name'))

    op.drop_table('autopkg_recipes')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_vendor'))
        batch_op.drop_index(batch_op.f('ix_apps_slug'))
        batch_op.drop_index(batch_op.f('ix_apps_bundle_id'))

    op.drop_table('apps')
    # ### end Alembic commands ###
