name: Publish to Test PyPi

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Build distro
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install 3.x
      - name: Build binary wheel and source tarbell
        run: uv build
      - name: Store distribution package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish distro to TestPyPI
    needs:
      - build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/patcherctl

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6.0.0
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution package to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
