name: Build and Release

on:
  workflow_dispatch:
    inputs:
      contributors:
        description: 'Contributors for this release'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build distro
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pypa/build
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build --user

      - name: Read release version
        id: read_version
        run: |
          VERSION=$(python3 -c 'import src.Patcher.__about__ as about; print(about.__version__)')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build binary wheel and source tarball
        run: python3 -m build

      - name: Store distribution package
        uses: actions/upload-artifact@v4
        with:
          name: patcher-${{ env.VERSION }}
          path: dist/

      - name: Sign distribution packages
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: |
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        with:
          name: Patcher ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./dist/*.tar.gz
            ./dist/*.whl
          body: |
            This release has been automatically generated by a GitHub Action.

            ## Installation Instructions
            > **🎉 Note**
            > Beginning with version 1.3.1, Patcher can now be installed via `pip`:
            > `python3 -m pip install patcherctl`

            For detailed installation instructions, please refer to the [Wiki](https://github.com/liquidz00/Patcher/wiki#installation) or the [README](https://github.com/liquidz00/Patcher/blob/main/README.md)

            ## Release notes
            ${{ steps.changelog.outputs.changelog }}

            ### Contributors
            ${{ github.event.inputs.contributors }}
