name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for this release (e.g., 1.0.0)'
        required: true
      contributors:
        description: 'Contributors for this release'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: patcher-${{ github.event.inputs.version }}
          path: dist/

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          reverse: 'true'

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          name: Patcher ${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./dist/*.tar.gz
            ./dist/*.whl
          body: |
            This release has been automatically generated by a GitHub Action.

            ## Installation Instructions
            For detailed installation instructions, please refer to the [Docs](https://patcher.liquidzoo.io) or the [README](https://github.com/liquidz00/Patcher/blob/main/README.md)

            ## Release notes
            ${{ steps.changelog.outputs.changelog }}

            ### Contributors
            ${{ github.event.inputs.contributors }}
